export const LOGIN_CALL = "LOGIN_CALL";
export const LOGOUT_CALL = "LOGOUT_CALL";
export const REGISTER_CALL = "REGISTER_CALL";

export const LOAD_USER = "LOADER_USER";
export const LOAD_USER_FAIL = "LOADER_USER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE";
